# Generated by Django 4.2.4 on 2023-09-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='expired',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='expired_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
