# Generated by Django 4.2.4 on 2023-09-03 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usertoken_expired_usertoken_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 5, 36, 58, 746189)),
        ),
    ]
